# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories: 
      - "/"
      - "/composite/style/github_actions"
      - "/composite/style/gofmt"
      - "/composite/style/shell"
      - "/composite/style/yaml"
      - "/setup-go"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

