name: "suggester / gofmt"
description: "Uses reviewdog to suggest go format changes."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - run: gofmt -w -s .
      shell: bash
    - uses: reviewdog/action-suggester@v1
      with:
        tool_name: gofmt
        filter_mode: 'file'
