name: "suggester / shell"
description: "Uses reviewdog to suggest shell script format changes. Enforces ShellCheck."

inputs:
  changed_shell_files:
    description: “list of changed shell files.”
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo "Detected changed shell files: ${{ inputs.changed_shell_files }}"
      shell: bash

    - uses: actions/checkout@v4

    - name: "ShellCheck"
      uses: reviewdog/action-shellcheck@v1
      with:
        reporter: 'github-pr-review'
        exclude: |
          ./vendor/*
          */vendor/*
        shellcheck_flags: |
          --external-sources -e=SC1091
