name: "suggester / shell"
description: "Uses reviewdog to suggest shell script format changes. Enforces ShellCheck."

inputs:
  changed_shell_files:
    description: “list of changed shell files.”
    required: true

runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.changed_shell_files }}
      shell: bash
    - uses: actions/checkout@v3
    - id: shellcheck_suggester
      uses: mathiasvr/command-output@v1
      with:
        run: |
          echo ${{ inputs.changed_shell_files }}
          for sh_file in ${{ inputs.changed_shell_files }}; do
            shellcheck -f diff $sh_file | patch -p1
          done
        shell: bash
      continue-on-error: true
    - name: suggester / shellcheck
      uses: reviewdog/action-suggester@v1
      with:
        level: 'warning'
        reporter: 'github-pr-review'
        tool_name: shellcheck
        filter_mode: 'file'

    - uses: reviewdog/action-shfmt@v1
      with:
        level: 'warning'
        reporter: 'github-pr-check'

    - name: "ShellCheck"
      if: ${{ steps.shellcheck_suggester.outputs.stderr }}
      uses: reviewdog/action-shellcheck@v1
      with:
        reporter: 'github-pr-check'
