# Copyright 2024 Knative Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Setup Go'
description: |
  This action sets up golang with the default version defined by the
  Knative project maintainers

inputs:
  go-version:
    description: |
      override the go version defined by the Knative project

    required: false

runs:
  using: "composite"
  steps:
    - name: determine go version
      shell: bash
      run: |
        GO_SETUP_VERSION="${{ inputs.go-version }}"

        if [[ -z "${GO_SETUP_VERSION}" ]]; then
          GO_SETUP_VERSION=1.22
        fi

        echo "GO_SETUP_VERSION=${GO_SETUP_VERSION}" >> $GITHUB_ENV

    - name: setup go ${ env.GO_SETUP_VERSION }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_SETUP_VERSION }}
