name: "suggester / yaml"
description: "Uses reviewdog to suggest yaml format changes."

inputs:
  changed_yaml_files:
    description: “list of changed yaml files.”
    required: true

env:
  YAMLLINT_RULES: "{extends: default, rules: {line-length: disable}}"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"   
    - run: pip install yamlfixer-opt-nc
      shell: bash
    - run: yamlfixer -C $YAMLLINT_RULES ${{ inputs.changed_yaml_files }}
      shell: bash
      continue-on-error: true
    - uses: reviewdog/action-suggester@v1
      with:
        tool_name: yamlfixer
        filter_mode: 'file'

    - uses: reviewdog/action-yamllint@v1
      with:
        yamllint_flags: >
          -d $YAMLLINT_RULES
          --no-warnings
          ${{ inputs.changed_yaml_files }}
        filter_mode: 'file'
