name: File Syncer
on:
  schedule:
    - cron: ''0 1 * * 0' # 6am Pacific, Sunday.'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Syncer
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          CONFIG_PATH: "sync/file-syncer-config.yaml"
          PR_LABELS: "skip-review"
          GIT_EMAIL: "automation@knative.team"
          GIT_USERNAME: "Knative Automation"
          GH_PAT: ${{ secrets.GH_PAT_FILE_SYNCER }}
